sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /rgbd_camera/depth/points/filtered
    max_range: 5
    point_subsample: 1
    padding_offset: 0.01
    padding_scale: 1.0
filtered_cloud_topic: filtered_cloud